SKILL_TREES = {
    "Combat": [
        "Muscle Memory", "Precise Blows", "Crushing Blows", "Fleet Footed",
        "Razor Focus", "Whirl", "Rend", "Strength Training",
        "Arrow Deflection", "Resolve", "Counterattack", "Sunder Armor",
        "Undying", "Deadly Precision", "Crippling Strikes", "Flood of Anger",
        "Swordsman", "Lightning Reflexes", "Cold Blood",
    ],
    "Signs": [
        "Aard Sweep", "Aard Intensity", "Aard Discharge",
        "Igni Intensity", "Igni Sign Intensity", "Melt Armor", "Firestream",
        "Quen Intensity", "Active Shield", "Quen Discharge",
        "Yrden Intensity", "Sustained Glyphs", "Magic Trap",
        "Axii Intensity", "Puppet", "Domination",
        "Sign Intensity",
    ],
    "Alchemy": [
        "Acquired Tolerance", "Heightened Tolerance", "Refreshment",
        "Protective Coating", "Synergy", "Killing Spree",
        "Hunter Instinct", "Tissue Transmutation", "Endure Pain",
        "Poisoned Blades", "Fixative", "Undying",
        "Delayed Recovery", "Efficiency", "Mutagenic Regeneration",
        "Adaptation", "Frenzy", "Bloodbath",
    ],
    "General": [
        "Griffin School Techniques", "Cat School Techniques", "Bear School Techniques",
        "Wolf School Techniques", "Heightened Tolerance", "Adrenaline Burst",
        "Survival Instinct", "Sun and Stars", "Gourmet", "Rage Management",
        "Metabolic Control", "Steady Aim",
    ],
}

MAIN_QUESTS = [
    # White Orchard
    "Lilac and Gooseberries", "The Beast of White Orchard",
    # Velen
    "Bloody Baron", "Ciri's Story: The King of the Wolves",
    "Ladies of the Wood", "Ciri's Story: Out of the Shadows",
    "The Whispering Hillock", "Return to Crookback Bog",
    # Novigrad
    "Broken Flowers", "Get Junior", "Pyres of Novigrad",
    "Novigrad Dreaming", "Favor for a Friend", "Count Reuven's Treasure",
    "The Play's the Thing", "A Poet Under Pressure", "An Eye for an Eye",
    "Deadly Plot", "Blindingly Obvious",
    # Skellige
    "Destination: Skellige", "The King is Dead – Long Live the King",
    "Echoes of the Past", "Nameless", "The Cave of Dreams",
    "Following the Thread", "To Bait a Forktail",
    "The Lord of Undvik", "Missing Son", "Possession", "The Sad Tale of the Grossbart Brothers",
    "King's Gambit",
    # Act 2
    "Battle Preparations", "Isle of Mists",
    "The Battle of Kaer Morhen",
    # Epilogue
    "Final Preparations", "Blood on the Battlefield",
    "Something Ends, Something Begins", "Tedd Deireadh, The Final Age",
    "Epilogue",
]

SIDE_QUESTS = [
    "A Towerful of Mice", "The Witcher's Forge", "Ghosts of the Past",
    "Of Swords and Dumplings", "Now or Never", "A Matter of Life and Death",
    "Cabaret", "Carnal Sins", "The Soldier Statuette", "The Merchant from Novigrad",
    "In Wolf's Clothing", "Wild at Heart", "Hunting a Witch", "Wandering in the Dark",
    "Family Matters", "A Barnful of Trouble", "Devil by the Well",
    "The Nilfgaardian Connection", "Dirty Funds", "Ciri's Room",
    "Thou Shalt Not Pass", "Last Rites", "A Greedy God",
    "Muire D'yaeblen", "Disturbance", "The Lord of Lust",
    "The Heroes' Pursuits", "Races: Crow's Perch",
]

CONTRACTS = [
    "Contract: Devil by the Well", "Contract: The Merry Widow",
    "Contract: Shrieker", "Contract: Swamp Thing",
    "Contract: Jenny o' the Woods", "Contract: Haunted House",
    "Contract: Oxenfurt Drunk", "Contract: The Apiarian Phantom",
    "Contract: Doors Slamming Shut", "Contract: Mystery of the Lighthouse",
    "Contract: Phantom of the Trade Route", "Contract: Strange Beast",
    "Contract: Missing Son", "Contract: Woodland Beast",
    "Contract: The Creature from Oxenfurt Forest", "Contract: Harpy Contract",
    "Contract: Basilisk",
]

WITCHER_GEAR_SETS = {
    "Griffin School": {
        "playstyle": "Signs build — boosts Sign intensity and stamina regeneration",
        "pieces": ["Griffin Steel Sword", "Griffin Silver Sword", "Griffin Armor",
                   "Griffin Trousers", "Griffin Boots", "Griffin Gauntlets"],
    },
    "Cat School": {
        "playstyle": "Fast attack — bonuses for light armor and fast sword attacks",
        "pieces": ["Feline Steel Sword", "Feline Silver Sword", "Feline Armor",
                   "Feline Trousers", "Feline Boots", "Feline Gauntlets"],
    },
    "Bear School": {
        "playstyle": "Tank / strong attack — bonuses for heavy armor",
        "pieces": ["Ursine Steel Sword", "Ursine Silver Sword", "Ursine Armor",
                   "Ursine Trousers", "Ursine Boots", "Ursine Gauntlets"],
    },
    "Wolf School": {
        "playstyle": "Balanced — adrenaline and general combat bonuses",
        "pieces": ["Wolven Steel Sword", "Wolven Silver Sword", "Wolven Armor",
                   "Wolven Trousers", "Wolven Boots", "Wolven Gauntlets"],
    },
    "Manticore School": {
        "playstyle": "Alchemy — boosts to potion duration and bomb damage",
        "pieces": ["Manticore Steel Sword", "Manticore Silver Sword", "Manticore Armor",
                   "Manticore Trousers", "Manticore Boots", "Manticore Gauntlets"],
    },
    "Viper School": {
        "playstyle": "Poison and sign damage — obtained in Blood and Wine",
        "pieces": ["Viper Steel Sword", "Viper Silver Sword", "Viper Armor",
                   "Viper Trousers", "Viper Boots", "Viper Gauntlets"],
    },
}

GEAR_SLOTS = ["Head", "Chest", "Gloves", "Boots", "Steel Sword", "Silver Sword", "Ranged"]

ALL_QUEST_NAMES = MAIN_QUESTS + SIDE_QUESTS + CONTRACTS

# ── Skill descriptions ──────────────────────────────────────────────────────
SKILL_DESCRIPTIONS = {
    # Combat
    "Muscle Memory": "Increases fast attack damage. Core skill for any fast-attack build.",
    "Precise Blows": "Increases fast attack critical hit chance and damage.",
    "Crushing Blows": "Increases strong attack critical hit chance and damage.",
    "Fleet Footed": "Reduces damage taken while dodging. Essential for light-armor builds.",
    "Razor Focus": "Instantly generates Adrenaline Points when entering combat.",
    "Whirl": "Continuous spinning fast attack hitting all surrounding enemies. Great for crowds.",
    "Rend": "Powerful charged strong attack that ignores armor. Best single-target damage skill.",
    "Strength Training": "Increases strong attack damage. Pairs with Bear School.",
    "Arrow Deflection": "Geralt deflects arrows with his sword while in guard stance.",
    "Resolve": "Reduces Adrenaline Point loss when taking damage. Keeps momentum in fights.",
    "Counterattack": "Parrying or dodging enemy attacks lets you follow up with a free counter.",
    "Sunder Armor": "Strong attacks reduce enemy armor. Stacks multiple times.",
    "Undying": "Spends all Adrenaline Points to survive a killing blow with 1 HP. Once per fight.",
    "Deadly Precision": "Each Adrenaline Point gives a chance to instantly kill a foe.",
    "Crippling Strikes": "Fast attacks have a chance to cause bleeding.",
    "Flood of Anger": "Spending Adrenaline Points increases Sign intensity.",
    "Swordsman": "Increases damage for both fast and strong attacks.",
    "Lightning Reflexes": "Slows time when firing a crossbow while airborne after a dodge.",
    "Cold Blood": "Each hit while in Whirl generates Adrenaline Points.",
    # Signs
    "Aard Sweep": "Aard becomes a 360° blast, hitting all enemies around Geralt.",
    "Aard Intensity": "Increases Aard Sign intensity and stagger/knockdown chance.",
    "Aard Discharge": "Enemies affected by Aard lose their armor.",
    "Igni Intensity": "Increases Igni Sign intensity and burning duration.",
    "Igni Sign Intensity": "Further boosts Igni damage output.",
    "Melt Armor": "Igni permanently reduces enemy armor with each hit.",
    "Firestream": "Igni becomes a sustained flamethrower stream instead of a burst.",
    "Quen Intensity": "Increases Quen shield strength and duration.",
    "Active Shield": "Quen becomes an active shield — absorb hits and heal from them.",
    "Quen Discharge": "When Quen shield breaks, it releases a shockwave stunning enemies.",
    "Yrden Intensity": "Increases Yrden trap damage and slow effect.",
    "Sustained Glyphs": "Yrden can maintain two traps simultaneously.",
    "Magic Trap": "Yrden traps also damage and slow aerial enemies like harpies.",
    "Axii Intensity": "Increases Axii Sign intensity and charm duration.",
    "Puppet": "Axii-charmed enemies fight alongside Geralt temporarily.",
    "Domination": "Axii can be cast instantly without charge-up time.",
    "Sign Intensity": "Increases all Sign intensities. The universal Signs boost.",
    # Alchemy
    "Acquired Tolerance": "Each known alchemy formula increases max toxicity. Lets you stack decoctions.",
    "Heightened Tolerance": "Potions don't consume toxicity until they wear off.",
    "Refreshment": "Each dose of a potion restores some vitality.",
    "Protective Coating": "Applying oils grants a temporary damage reduction bonus.",
    "Synergy": "Each mutagen slotted alongside matching skills boosts its effect.",
    "Killing Spree": "Each kill while a decoction is active extends the decoction duration.",
    "Hunter Instinct": "Critical hits deal double damage while under a decoction effect.",
    "Tissue Transmutation": "Killing enemies while under decoction effects increases max vitality.",
    "Endure Pain": "Increases max vitality while toxicity is above 0.",
    "Poisoned Blades": "Oil applied to blades has a chance to poison enemies.",
    "Fixative": "Weapon oils last through 50% more hits than normal.",
    "Delayed Recovery": "Potion effects don't expire until toxicity drops to near 0.",
    "Efficiency": "Bombs can be thrown more times per combat encounter.",
    "Mutagenic Regeneration": "Regenerate vitality when toxicity is above 0.",
    "Adaptation": "Mutagen bonuses are 50% stronger.",
    "Frenzy": "If toxicity is above 0, time slows whenever an enemy attempts a counter-attack.",
    "Bloodbath": "Each kill in combat regenerates vitality.",
    # General
    "Griffin School Techniques": "Each piece of Griffin gear increases Sign intensity by 5%.",
    "Cat School Techniques": "Each piece of Cat gear increases fast attack damage by 6% (light armor).",
    "Bear School Techniques": "Each piece of Bear gear increases strong attack damage by 5% (heavy armor).",
    "Wolf School Techniques": "Each piece of Wolf gear increases Adrenaline Point gain by 5%.",
    "Heightened Tolerance": "Increases max toxicity threshold.",
    "Adrenaline Burst": "Using Signs generates Adrenaline Points.",
    "Survival Instinct": "Increases max vitality significantly.",
    "Sun and Stars": "Regenerate vitality during the day; stamina regenerates faster at night.",
    "Gourmet": "Food effects last for the entire fight (not just a few seconds).",
    "Rage Management": "Adrenaline Points can be spent to cast Signs without stamina cost.",
    "Metabolic Control": "Increases max toxicity, letting you stack more potions.",
    "Steady Aim": "Slows time while aiming the crossbow.",
}

# ── Bestiary ────────────────────────────────────────────────────────────────
BESTIARY = [
    # Necrophages
    {"name": "Drowner", "category": "Necrophage", "sign": "Igni", "oil": "Necrophage Oil",
     "bombs": "Devil's Puffball",
     "tactic": "Use Igni to ignite. Watch for the grab — dodge sideways. They respawn near water at night. Necrophage oil is essential."},
    {"name": "Ghoul", "category": "Necrophage", "sign": "Igni", "oil": "Necrophage Oil",
     "bombs": "Devil's Puffball",
     "tactic": "Fast attackers that swarm in groups. Igni or a bomb for crowds. Stay mobile and oil your silver sword."},
    {"name": "Alghoul", "category": "Necrophage", "sign": "Aard", "oil": "Necrophage Oil",
     "bombs": "Grapeshot",
     "tactic": "Use Aard to knock off its defensive spines — much harder to fight when they're up. Attack only after staggering it."},
    {"name": "Rotfiend", "category": "Necrophage", "sign": "Igni", "oil": "Necrophage Oil",
     "bombs": "Devil's Puffball",
     "tactic": "WARNING: Do NOT kill the last one with fire or an explosion — triggers a lethal death explosion. Finish with a quick sword strike only."},
    {"name": "Nekker", "category": "Necrophage", "sign": "Igni", "oil": "Necrophage Oil",
     "bombs": "Devil's Puffball",
     "tactic": "Swarm attackers. Igni or Aard sweep to control groups. Destroy their nests to stop respawning."},
    {"name": "Foglet", "category": "Necrophage", "sign": "Yrden", "oil": "Necrophage Oil",
     "bombs": "Moon Dust",
     "tactic": "Yrden forces it into physical form — without it the Foglet is nearly invulnerable. Moon Dust bombs also work."},
    {"name": "Water Hag", "category": "Necrophage", "sign": "Igni", "oil": "Necrophage Oil",
     "bombs": "Devil's Puffball",
     "tactic": "Fast and aggressive. Lead it away from water to fight on land. Igni disrupts its attacks."},
    {"name": "Bilge Hag", "category": "Necrophage", "sign": "Igni", "oil": "Necrophage Oil",
     "bombs": "Devil's Puffball",
     "tactic": "Tougher Water Hag variant found in Skellige. Keep moving, use Igni, and don't let it drag you into water."},
    # Specters
    {"name": "Wraith", "category": "Specter", "sign": "Yrden", "oil": "Specter Oil",
     "bombs": "Moon Dust",
     "tactic": "Yrden is mandatory — without it a Wraith teleports constantly and deals reduced damage from swords. Moon Dust forces physical form."},
    {"name": "Noonwraith", "category": "Specter", "sign": "Yrden", "oil": "Specter Oil",
     "bombs": "Moon Dust",
     "tactic": "Splits into copies. Trap the real one with Yrden. A mirror or sun object often weakens it. Appears at noon near cursed locations."},
    {"name": "Nightwraith", "category": "Specter", "sign": "Yrden", "oil": "Specter Oil",
     "bombs": "Moon Dust",
     "tactic": "Appears only at night. Same Yrden approach as Noonwraith. Usually tied to a specific haunted location."},
    # Beasts
    {"name": "Wolf", "category": "Beast", "sign": "Axii", "oil": "Beast Oil",
     "bombs": "Samum",
     "tactic": "Pack hunters. Use Axii to turn one against the others. Straightforward otherwise — Beast oil and keep moving."},
    {"name": "Bear", "category": "Beast", "sign": "Quen", "oil": "Beast Oil",
     "bombs": "Grapeshot",
     "tactic": "Tanky with a lethal charge. Keep Quen active. Roll to the side of charges — never directly backwards. Patient, deliberate strikes only."},
    {"name": "Werewolf", "category": "Cursed", "sign": "Yrden", "oil": "Cursed Oil",
     "bombs": "Moon Dust",
     "tactic": "Regenerates health rapidly. Yrden slows regeneration. Moon Dust or Cursed oil required. Attack during its own attack animations."},
    # Draconids
    {"name": "Wyvern", "category": "Draconid", "sign": "Aard", "oil": "Draconid Oil",
     "bombs": "Grapeshot",
     "tactic": "Wait for its dive attack, roll past it, then strike. Aard knocks it down mid-flight. Crossbow pulls it down when it stays airborne."},
    {"name": "Basilisk", "category": "Draconid", "sign": "Aard", "oil": "Draconid Oil",
     "bombs": "Grapeshot",
     "tactic": "Dodge the petrification beam — roll sideways, never stand still. Aard disrupts its attacks. Similar tactics to Wyvern."},
    {"name": "Cockatrice", "category": "Draconid", "sign": "Aard", "oil": "Draconid Oil",
     "bombs": "Grapeshot",
     "tactic": "Erratic movement and quick slashes. Roll INTO its attacks rather than away. Aard to stagger mid-combo."},
    # Hybrids
    {"name": "Griffin", "category": "Hybrid", "sign": "Aard", "oil": "Hybrid Oil",
     "bombs": "Grapeshot",
     "tactic": "Classic early-game contract. Hover attack is telegraphed — roll right. Use Aard when it dives. Crossbow to ground it if it refuses to land."},
    {"name": "Harpy", "category": "Hybrid", "sign": "Aard", "oil": "Hybrid Oil",
     "bombs": "Grapeshot",
     "tactic": "Aerial dive-bombers. Aard or crossbow to knock from the air. They dive-bomb in straight lines — dodge to the side."},
    # Insectoids
    {"name": "Endrega", "category": "Insectoid", "sign": "Igni", "oil": "Insectoid Oil",
     "bombs": "Grapeshot",
     "tactic": "Igni works well. Destroy egg sacs nearby to stop reinforcements. Watch for acid spit — keep mobile."},
    {"name": "Arachas", "category": "Insectoid", "sign": "Aard", "oil": "Insectoid Oil",
     "bombs": "Grapeshot",
     "tactic": "Armored shell deflects most attacks. Aard to flip it and expose the soft underbelly. Attacks from underground — watch your feet."},
    # Elementals
    {"name": "Earth Elemental", "category": "Elementa", "sign": "None", "oil": "Elementa Oil",
     "bombs": "Dimeritium Bomb",
     "tactic": "Signs are largely useless here. Dimeritium bomb shuts down any magic abilities. Oil your blade and be very patient — hits extremely hard."},
    {"name": "Fire Elemental", "category": "Elementa", "sign": "Aard", "oil": "Elementa Oil",
     "bombs": "Dimeritium Bomb",
     "tactic": "Aard disrupts its fire attacks. Dimeritium to neutralize. DO NOT use Igni. Stay far back during flame eruption phase."},
    {"name": "Ice Elemental", "category": "Elementa", "sign": "Igni", "oil": "Elementa Oil",
     "bombs": "Dimeritium Bomb",
     "tactic": "Igni melts its defenses over time. Dimeritium to shut down ice beams. The ice beam slows Geralt — dodge it aggressively."},
    # Relicts
    {"name": "Leshen", "category": "Relict", "sign": "Igni", "oil": "Relict Oil",
     "bombs": "Devil's Puffball",
     "tactic": "Use Aard sweep to cut down its crow swarm first. Kill wolves it summons before focusing the Leshen. Burn the body with Igni to prevent regeneration."},
    {"name": "Fiend", "category": "Relict", "sign": "Yrden", "oil": "Relict Oil",
     "bombs": "Dimeritium Bomb",
     "tactic": "Its third eye stuns you — face away from it or use Dimeritium bomb. Yrden slows its charge. Always attack from the flanks."},
    # Vampires
    {"name": "Ekimmara", "category": "Vampire", "sign": "Yrden", "oil": "Vampire Oil",
     "bombs": "Moon Dust",
     "tactic": "Heals from wounds it inflicts. Keep Quen up at all times. Yrden slows it. Stay very aggressive so it can't heal."},
    {"name": "Katakan", "category": "Vampire", "sign": "Yrden", "oil": "Vampire Oil",
     "bombs": "Moon Dust",
     "tactic": "Turns invisible between attacks. Yrden forces it visible. Moon Dust also works. Quen is essential — it hits extremely fast."},
    {"name": "Bruxae", "category": "Vampire", "sign": "Yrden", "oil": "Vampire Oil",
     "bombs": "Moon Dust",
     "tactic": "Screeches to stagger — stay mobile. Yrden grounds it. Crossbow during its recovery animation is very effective."},
    {"name": "Toad Prince", "category": "Cursed", "sign": "Igni", "oil": "Cursed Oil",
     "bombs": "Grapeshot",
     "tactic": "Boss fight. Dodge the acid spit sideways. Attack the tongue when it lunges — big window. Igni to the face after dodging. Keep Quen active."},
]

BESTIARY_CATEGORIES = sorted(set(m["category"] for m in BESTIARY))

# ── Build Templates ──────────────────────────────────────────────────────────
BUILD_TEMPLATES = [
    {
        "id": "signs-griffin",
        "name": "Signs Master",
        "school": "Griffin School",
        "playstyle": "Maximum Sign intensity — Igni and Quen dominate",
        "description": "The most versatile beginner build. Quen keeps you alive, Igni burns everything. Griffin gear amplifies all Sign intensity.",
        "recommended_gear": "Griffin School (all 6 pieces)",
        "pros": ["Very safe — Quen absorbs damage", "Works on all enemy types", "High burst damage with Igni"],
        "cons": ["Stamina management required", "Weak vs. Elementals that resist Signs"],
        "skills": [
            {"name": "Sign Intensity", "level": 5, "equipped": True, "category": "General"},
            {"name": "Griffin School Techniques", "level": 1, "equipped": True, "category": "General"},
            {"name": "Igni Intensity", "level": 5, "equipped": True, "category": "Signs"},
            {"name": "Melt Armor", "level": 5, "equipped": True, "category": "Signs"},
            {"name": "Quen Intensity", "level": 5, "equipped": True, "category": "Signs"},
            {"name": "Active Shield", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Aard Intensity", "level": 5, "equipped": True, "category": "Signs"},
            {"name": "Sustained Glyphs", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Resolve", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Flood of Anger", "level": 3, "equipped": True, "category": "Combat"},
            {"name": "Adrenaline Burst", "level": 3, "equipped": True, "category": "General"},
            {"name": "Rage Management", "level": 3, "equipped": True, "category": "General"},
        ],
    },
    {
        "id": "fast-cat",
        "name": "Feline Assassin",
        "school": "Cat School",
        "playstyle": "Bleed damage, fast attacks, light armor bonuses",
        "description": "Extreme fast attack build. Cat School gear gives massive bonuses to fast attack in light armor. Bleeds and crits kill most enemies quickly.",
        "recommended_gear": "Cat School (all 6 pieces)",
        "pros": ["Fastest kill speed on most enemies", "High mobility", "Great for humanoid enemies"],
        "cons": ["Fragile — light armor means more damage taken", "Needs precise dodge timing"],
        "skills": [
            {"name": "Cat School Techniques", "level": 1, "equipped": True, "category": "General"},
            {"name": "Muscle Memory", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Precise Blows", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Whirl", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Fleet Footed", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Razor Focus", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Crippling Strikes", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Swordsman", "level": 3, "equipped": True, "category": "Combat"},
            {"name": "Quen Intensity", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Active Shield", "level": 1, "equipped": True, "category": "Signs"},
            {"name": "Adrenaline Burst", "level": 3, "equipped": True, "category": "General"},
            {"name": "Acquired Tolerance", "level": 3, "equipped": True, "category": "Alchemy"},
        ],
    },
    {
        "id": "tank-bear",
        "name": "Iron Bear",
        "school": "Bear School",
        "playstyle": "Heavy armor, strong attacks, maximum survivability",
        "description": "Unkillable tank build. Bear gear stacks with strong attack and heavy armor perks. Rend is your primary damage tool — charges through armor.",
        "recommended_gear": "Bear School (all 6 pieces)",
        "pros": ["Extremely high survivability", "Rend ignores enemy armor", "Arrow Deflection handles ranged enemies"],
        "cons": ["Slower playstyle", "Cat/Griffin builds outrun it on DPS"],
        "skills": [
            {"name": "Bear School Techniques", "level": 1, "equipped": True, "category": "General"},
            {"name": "Strength Training", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Crushing Blows", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Rend", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Arrow Deflection", "level": 3, "equipped": True, "category": "Combat"},
            {"name": "Resolve", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Undying", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Quen Intensity", "level": 5, "equipped": True, "category": "Signs"},
            {"name": "Active Shield", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Survival Instinct", "level": 3, "equipped": True, "category": "General"},
            {"name": "Adrenaline Burst", "level": 3, "equipped": True, "category": "General"},
            {"name": "Acquired Tolerance", "level": 3, "equipped": True, "category": "Alchemy"},
        ],
    },
    {
        "id": "alchemy-manticore",
        "name": "Alchemist",
        "school": "Manticore School",
        "playstyle": "Potions, decoctions, and bombs — maximized alchemy",
        "description": "Decoction stacking build. Acquired Tolerance lets you run multiple decoctions simultaneously. Manticore gear extends their duration massively.",
        "recommended_gear": "Manticore School (all 6 pieces)",
        "pros": ["Absurd sustained damage from decoctions", "Bombs handle most crowd control", "Self-sustaining via Refreshment"],
        "cons": ["Requires significant crafting investment", "Needs prep between fights"],
        "skills": [
            {"name": "Acquired Tolerance", "level": 5, "equipped": True, "category": "Alchemy"},
            {"name": "Heightened Tolerance", "level": 5, "equipped": True, "category": "Alchemy"},
            {"name": "Refreshment", "level": 5, "equipped": True, "category": "Alchemy"},
            {"name": "Protective Coating", "level": 5, "equipped": True, "category": "Alchemy"},
            {"name": "Synergy", "level": 5, "equipped": True, "category": "Alchemy"},
            {"name": "Killing Spree", "level": 3, "equipped": True, "category": "Alchemy"},
            {"name": "Delayed Recovery", "level": 3, "equipped": True, "category": "Alchemy"},
            {"name": "Efficiency", "level": 3, "equipped": True, "category": "Alchemy"},
            {"name": "Resolve", "level": 3, "equipped": True, "category": "Combat"},
            {"name": "Muscle Memory", "level": 3, "equipped": True, "category": "Combat"},
            {"name": "Quen Intensity", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Adrenaline Burst", "level": 3, "equipped": True, "category": "General"},
        ],
    },
    {
        "id": "balanced-wolf",
        "name": "Wolf Pack",
        "school": "Wolf School",
        "playstyle": "Balanced adrenaline build — proficient at everything",
        "description": "The classic Witcher build. Wolf School techniques reward mixing all combat styles. Adrenaline powers everything up and Signs augment combat.",
        "recommended_gear": "Wolf School (all 6 pieces)",
        "pros": ["Flexible — handles any situation", "Adrenaline synergizes everything", "Great all-rounder"],
        "cons": ["Not the best at any single thing", "Requires more skill points to shine"],
        "skills": [
            {"name": "Wolf School Techniques", "level": 1, "equipped": True, "category": "General"},
            {"name": "Adrenaline Burst", "level": 5, "equipped": True, "category": "General"},
            {"name": "Muscle Memory", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Crushing Blows", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Razor Focus", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Resolve", "level": 5, "equipped": True, "category": "Combat"},
            {"name": "Flood of Anger", "level": 3, "equipped": True, "category": "Combat"},
            {"name": "Igni Intensity", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Quen Intensity", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Active Shield", "level": 3, "equipped": True, "category": "Signs"},
            {"name": "Acquired Tolerance", "level": 3, "equipped": True, "category": "Alchemy"},
            {"name": "Synergy", "level": 3, "equipped": True, "category": "Alchemy"},
        ],
    },
]
